version: '3.8'
services:
    api:
        container_name: api
        build: ./api
        command: yarn run start
        volumes:
            - ./api:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        links:
            - database
#        environment:
#            DATABASE_URL: postgres://todoapp@postgres/todos
    # mongodb:
    #     container_name: mongodb
    #     image: mongo
    #     restart: always
    #     volumes:
    #         - ./api/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: root
    #         MONGO_INITDB_ROOT_PASSWORD: passwoord
    #         MONGO_INITDB_DATABASE: db
    database:
        image: mysql:8.0.32-debian
        volumes:
            - /var/lib/mysql
            - "./apiconfig/database_schema.sql:/docker-entrypoint-initdb.d/1.sql"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: fleeter