version: '3.8'
services:
    api:
        container_name: api
        build: ./api
        command: yarn run start
        volumes:
            - ./api:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        links:
            - mongodb
#        environment:
#            DATABASE_URL: postgres://todoapp@postgres/todos
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        volumes:
            - ./api/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: passwoord
            MONGO_INITDB_DATABASE: db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_BASICAUTH_USERNAME=user
            - ME_CONFIG_BASICAUTH_PASSWORD=password
        links:
            - mongodb
        ports:
            - 8081:8081
        restart: unless-stopped